// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: configuration-item.sql

package repository

import (
	"context"
)

const findAllConfigurationItems = `-- name: FindAllConfigurationItems :many
SELECT id, namespace, key, label, value, content_type, is_feature_flag, enabled, created_at, updated_at, is_deleted FROM configuration_items
`

func (q *Queries) FindAllConfigurationItems(ctx context.Context) ([]ConfigurationItem, error) {
	rows, err := q.db.Query(ctx, findAllConfigurationItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigurationItem
	for rows.Next() {
		var i ConfigurationItem
		if err := rows.Scan(
			&i.ID,
			&i.Namespace,
			&i.Key,
			&i.Label,
			&i.Value,
			&i.ContentType,
			&i.IsFeatureFlag,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
