// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ConfigurationItem struct {
	ID            uuid.UUID   `json:"id"`
	Namespace     string      `json:"namespace"`
	Key           string      `json:"key"`
	Label         pgtype.Text `json:"label"`
	Value         string      `json:"value"`
	ContentType   pgtype.Text `json:"content_type"`
	IsFeatureFlag pgtype.Bool `json:"is_feature_flag"`
	Enabled       pgtype.Bool `json:"enabled"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	IsDeleted     bool        `json:"is_deleted"`
}

type Player struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
